# Generated by Django 4.0.3 on 2024-05-03 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('voca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.voca')),
            ],
        ),
    ]
