# Generated by Django 4.0.3 on 2024-05-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voca',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
